### ISSUE TITLE
Detectron feature extraction

### ISSUE THREAD

**Issue by leotam** [LuoweiZhou/VLP#7]
Might it be possible to release the script to extract features using the Detectron model?  Probably something similar to this https://github.com/ruotianluo/ImageCaptioning.pytorch/blob/master/scripts/prepro_feats.py that was used to generate the region_feat_gvd_wo_bgd/trainval .npz features and class probabilities?

**Comment by LuoweiZhou** [comment]
We plan to release the feature extraction code soon. Please stay tuned.

**Comment by yuewang-cuhk** [comment]
Hey, I am also looking forward to the release of the feature extraction code! Before that, could you also point out which repos we can refer to for the detection feature extraction and share some guidance about how to implement it in order to obtain the same features as yours? Thanks:)

**Comment by LuoweiZhou** [comment]
@yuewang-cuhk You can refer to the Pythia script for now: https://github.com/facebookresearch/pythia/blob/7e593fc66ad74e22d218300df692e254f53d9375/pythia/scripts/features/extract_features.py#L193
The main difference is that when we do class-wise NMS, we use the per-class bbox coordinates rather than the coordinates from RPN. More details will come soon.
![image](https://user-images.githubusercontent.com/14948792/67132010-14c08480-f1d5-11e9-876d-fc8608108c5d.png)
(Note: ignore the note on `__background__` because background class is deprecated, `cls_ind` starts from 1)

**Comment by yuewang-cuhk** [comment]
@LuoweiZhou Hi, it seems the detectron package is deprecated and now [detectron2](https://github.com/facebookresearch/detectron2) is released. I would like to ask whether I can directly use detectron2 for feature extraction to produce the same visual features as yours? Does it have any influence if I adopt your pre-trained model and fine-tune it on a new dataset with the visual features extracted by detectron2? Thanks

**Comment by LuoweiZhou** [comment]
It's not compatible according to the official doc: https://detectron2.readthedocs.io/notes/compatibility.html#compatibility-with-detectron

**Comment by leotam** [comment]
Just to circle back around, the pointer to the Pythia script was quite helpful.  There was some minor modification with Detectron since some pieces moved around.  For instance, there was a missing function (im_detect_bbox) in test.engine infer_engine that was found instead in core/test.py. I do read what you mean about not using the RPN coordinates.  Just to be precise, it means you're feeding in the coordinates additionally to im_detect_bbox with a more accurate method?  Or is the idea that you perform the classwise NMS, then once those are 'locked in', they're feed back in to the feature extraction to grab the correct features?  Would another method just be to grab the highest confidence detection from the RPN? Thanks again

**Comment by LuoweiZhou** [comment]
@leotam the feature remains the same. The more precise way to get the bbox coordinates is to use the class-wise bbox coordinates suppressed after class-wise NMS (this repo) rather than the class-agnostic bbox coordinates from RPN (pythia and [gvd](https://github.com/facebookresearch/grounded-video-description)).

**Comment by LuoweiZhou** [comment]
In [Pythia](https://github.com/facebookresearch/pythia/blob/7e593fc66ad74e22d218300df692e254f53d9375/pythia/scripts/features/extract_features.py#L192), the coordinates used for class-wise NMS are the same one from RPN for all the classes.
